name: Cypress Tests

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci

      - name: Build server
        working-directory: ./server
        run: npm run build
        env:
          MONGODB_URI: mongodb://localhost:27017/tpktest
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Start server
        working-directory: ./server
        env:
          MONGODB_URI: mongodb://localhost:27017/tpktest
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          npm start &
          # Simple health check for server
          timeout=30
          until $(curl --output /dev/null --silent --head --fail http://localhost:3001); do
            if [ $timeout -eq 0 ]; then
              echo "Timeout waiting for server"
              exit 1
            fi
            printf '.'
            timeout=$((timeout-1))
            sleep 1
          done
          echo "Server is up!"

      - name: Start client
        working-directory: ./client
        run: |
          npm run dev &
          # Simple health check for client
          timeout=30
          until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
            if [ $timeout -eq 0 ]; then
              echo "Timeout waiting for client"
              exit 1
            fi
            printf '.'
            timeout=$((timeout-1))
            sleep 1
          done
          echo "Client is up!"

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          component: true
          browser: chrome
          install: false
        env:
          MONGODB_URI: mongodb://localhost:27017/tpktest
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          browser: chrome
          install: false
        env:
          MONGODB_URI: mongodb://localhost:27017/tpktest
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Upload Cypress screenshots if tests fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: client/cypress/videos