name: Cypress Tests

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci

      - name: Build server
        working-directory: ./server
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Start server
        working-directory: ./server
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          echo "Starting server with MONGODB_URI=${MONGODB_URI}"
          node dist/server.js &
          sleep 10
          if ! curl -s http://localhost:3001 > /dev/null; then
            echo "Server failed to start"
            exit 1
          fi

      - name: Start client
        working-directory: ./client
        run: |
          npm run dev &
          sleep 10
          if ! curl -s http://localhost:3000 > /dev/null; then
            echo "Client failed to start"
            exit 1
          fi

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          component: true
          browser: chrome
          install: false
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          browser: chrome
          install: false
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Upload Cypress screenshots if tests fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: client/cypress/videos