name: Cypress Tests

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm ci

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Start server
        working-directory: ./server
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: npm start & npx wait-on http://localhost:3001

      - name: Start client
        working-directory: ./client
        run: npm run dev & npx wait-on http://localhost:3000

      - name: Run Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          component: true
          browser: chrome
          install: false

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          browser: chrome
          install: false

      - name: Upload Cypress screenshots if tests fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: client/cypress/videos